name: documentation release version
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
    
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy_docs_dev:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true
          python-version: '3.13'
          activate-environment: true
      - name: Install Hatch
        run: uv pip install --upgrade --system hatch
      - name: Deploy release version of docs
        run: hatch run docs:ci-build --push dev
