name: documentation
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install mkdocs-material mkdocs-autorefs mkdocstrings mkdocstrings-python mkdocs-gen-files mkdocs-literate-nav mkdocs-section-index mkdocs-jupyter mkdocs-git-revision-date-localized-plugin mkdocs-include-markdown-plugin black
      - run: mkdocs gh-deploy --force
