name: test

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }} numpy=${{ matrix.numpy }} pandas=${{ matrix.pandas }} polars=${{ matrix.polars }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        numpy: ['numpy-2.x', 'numpy-legacy']
        pandas: ['pandas-2.x', 'pandas-3.x']
        polars: ['polars', 'polars-compat']
        exclude:
          # pandas-3.x not supported on 3.9/3.10
          - python-version: '3.10'
            pandas: 'pandas-3.x'
          # numpy<2 not supported from 3.13 onwards
          - python-version: ['3.13','3.14']
            numpy: 'numpy-legacy'

    steps:
    - uses: actions/checkout@v6.0.2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        version: "latest"
        enable-cache: true

    - name: Run tests for ${{ matrix.python-version }}
      run: uvx hatch test --python ${{ matrix.python-version }} -i numpy=${{ matrix.numpy }} -i pandas=${{ matrix.pandas }} -i polars=${{ matrix.polars }}

  run_tests_python_39:
    name: Python 3.9
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v6.0.2

    - name: Set up Python 3.9
      uses: actions/setup-python@v6.2.0
      with:
        python-version: "3.9"

    - name: Set up uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        version: "latest"
        enable-cache: true

    - name: Run tests
      run: uvx -w "virtualenv<21" hatch test --python 3.9
